<!DOCTYPE html>
<html>
<head>
    <title>NG Report Analysis</title>
    <style>
        body { 
            font-family: Arial, sans-serif; 
            margin: 20px;
            font-size: 12px;
        }
        .header { 
            text-align: center; 
            margin-bottom: 20px; 
        }
        .summary-cards {
            margin: 20px 0;
            display: flex;
            justify-content: space-between;
        }
        .summary-card {
            border: 1px solid #ddd;
            padding: 10px;
            width: 30%;
            text-align: center;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f5f5f5;
        }
        .footer {
            margin-top: 30px;
            font-size: 10px;
            text-align: right;
        }
        .status-badge {
            padding: 3px 8px;
            border-radius: 3px;
            color: white;
            font-size: 10px;
        }
        .status-diperbaiki { background-color: #28a745; }
        .status-pending { background-color: #ffc107; }
        .status-scrap { background-color: #dc3545; }
        .status-rework { background-color: #17a2b8; }
    </style>
</head>
<body>
    <div class="header">
        <h2>NG Report Analysis</h2>
        <p>Generated on: {{ $printDate }}</p>
    </div>

    <div class="summary-cards">
        <div class="summary-card">
            <h3>Total NG</h3>
            <p>{{ number_format($summary['total_ng']) }}</p>
        </div>
        <div class="summary-card">
            <h3>Average NG %</h3>
            <p>{{ number_format($summary['avg_ng_percentage'], 2) }}%</p>
        </div>
        <div class="summary-card">
            <h3>Most Common NG</h3>
            <p>{{ $summary['most_common_ng'] ?? 'N/A' }}</p>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Machine</th>
                <th>Product</th>
                <th>Operator</th>
                <th>NG Type</th>
                <th>Total NG</th>
                <th>NG %</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($reports as $report)
                <tr>
                    <td>{{ $report->date }}</td>
                    <td>{{ $report->machine_name }}</td>
                    <td>{{ $report->product_name }}</td>
                    <td>{{ $report->operator_name }}</td>
                    <td>{{ $report->ng_type }}</td>
                    <td>{{ $report->total_ng }}</td>
                    <td>{{ $report->ng_percentage }}%</td>
                    <td>
                        <span class="status-badge status-{{ $report->status }}">
                            {{ ucfirst($report->status) }}
                        </span>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by: {{ $printedBy }}</p>
    </div>
</body>
</html>