<!DOCTYPE html>
<html>
<head>
    <title>Pareto Analysis Report</title>
    <style>
        body { font-family: Arial, sans-serif; }
        .header { text-align: center; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f4f4f4; }
        .footer { text-align: right; font-size: 12px; margin-top: 20px; }
    </style>
</head>
<body>
    <div class="header">
        <h2>Pareto Analysis Report</h2>
        <div>Period: {{ date('d/m/Y', strtotime($startDate)) }} - {{ date('d/m/Y', strtotime($endDate)) }}</div>
        <div>Machine: {{ $machine }}</div>
        <div>Product: {{ $product }}</div>
        <div>Shift: {{ $shift }}</div>
    </div>

    @if(isset($chartImage))
    <div class="chart-container" style="margin: 20px 0;">
        <img src="{{ $chartImage }}" style="width: 100%; max-width: 800px;">
    </div>
    @endif

    <table>
        <thead>
            <tr>
                <th>NG Type</th>
                <th>Count</th>
                <th>Percentage</th>
                <th>Cumulative %</th>
            </tr>
        </thead>
        <tbody>
            @foreach($paretoData as $data)
            <tr>
                <td>{{ $data['defect'] }}</td>
                <td>{{ $data['count'] }}</td>
                <td>{{ number_format($data['percentage'], 2) }}%</td>
                <td>{{ number_format($data['cumulative'], 2) }}%</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <div>Generated by: {{ $printedBy }}</div>
        <div>Date: {{ now()->format('d/m/Y H:i:s') }}</div>
    </div>
</body>
</html>