<!DOCTYPE html>
<html>
<head>
    <title>Pareto Analysis Report</title>
    <style>
        body { font-family: Arial, sans-serif; }
        .header { text-align: center; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f4f4f4; }
        .footer { text-align: right; font-size: 12px; margin-top: 20px; }
    </style>
</head>
<body>
    <div class="header">
        <h2>Pareto Analysis Report</h2>
        <div>Period: <?php echo e(date('d/m/Y', strtotime($startDate))); ?> - <?php echo e(date('d/m/Y', strtotime($endDate))); ?></div>
        <div>Machine: <?php echo e($machine); ?></div>
        <div>Product: <?php echo e($product); ?></div>
        <div>Shift: <?php echo e($shift); ?></div>
    </div>

    <?php if(isset($chartImage)): ?>
    <div class="chart-container" style="margin: 20px 0;">
        <img src="<?php echo e($chartImage); ?>" style="width: 100%; max-width: 800px;">
    </div>
    <?php endif; ?>

    <table>
        <thead>
            <tr>
                <th>NG Type</th>
                <th>Count</th>
                <th>Percentage</th>
                <th>Cumulative %</th>
            </tr>
        </thead>
        <tbody>
            <?php $__currentLoopData = $paretoData; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $data): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
            <tr>
                <td><?php echo e($data['defect']); ?></td>
                <td><?php echo e($data['count']); ?></td>
                <td><?php echo e(number_format($data['percentage'], 2)); ?>%</td>
                <td><?php echo e(number_format($data['cumulative'], 2)); ?>%</td>
            </tr>
            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
        </tbody>
    </table>

    <div class="footer">
        <div>Generated by: <?php echo e($printedBy); ?></div>
        <div>Date: <?php echo e(now()->format('d/m/Y H:i:s')); ?></div>
    </div>
</body>
</html><?php /**PATH /home/abdulazizurrohman/Downloads/11-EzzyIndustri-ftur-PDCA/resources/views/pdf/pareto-analysis.blade.php ENDPATH**/ ?>